# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-12 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdjangoapp', '0002_testdb_bian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='weibotable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('local', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
