# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-13 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdjangoapp', '0004_weibotable_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibotable',
            name='img',
        ),
    ]
