# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-14 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdjangoapp', '0005_remove_weibotable_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibotable',
            name='image',
            field=models.ImageField(default='', upload_to='images', verbose_name='图片'),
        ),
    ]
