# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import testdjangoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testdjangoapp', '0006_weibotable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='weibotable',
            name='commitnum',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='weibotable',
            name='image',
            field=models.ImageField(default='', upload_to=testdjangoapp.models.custom_path, verbose_name='图片'),
        ),
    ]
