# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdjangoapp', '0007_auto_20190115_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weibotable',
            name='image',
        ),
        migrations.AlterField(
            model_name='weibotable',
            name='commitnum',
            field=models.IntegerField(default=0),
        ),
    ]
