# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdjangoapp', '0008_auto_20190115_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('weiboname', models.CharField(max_length=20)),
                ('commitname', models.CharField(max_length=20)),
            ],
        ),
    ]
