# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdjangoapp', '0009_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='time',
            field=models.CharField(default=111, max_length=20),
            preserve_default=False,
        ),
    ]
