# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-16 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdjangoapp', '0012_auto_20190115_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='starlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestared', models.CharField(max_length=20)),
                ('stared', models.CharField(max_length=20)),
            ],
        ),
    ]
