# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-05 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdjangoapp', '0014_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='name',
        ),
    ]
